### ISSUE TITLE
Sort bags command

### ISSUE THREAD

**Issue by chrisblossom** [DengSir/tdPack2#1]
Is it possible to sort bags via a command? If not, is it possible to add this feature? I'd like a create a hotkey/macro I can press to sort my bags.

**Comment by DengSir** [comment]
The features already implemented.
`/tdp [asc|desc]` Sort all bags
`/tdp bag [asc|desc]` Sort bags
`/tdp bank [asc|desc]` Sort bank
`/tdp save` Save to bank

**Comment by dewbjorn** [comment]
@DengSir is there a way of only sorting *specific* bags?
