### ISSUE TITLE
自动保存到银行可配置

### ISSUE THREAD

**Issue by sfpprxy** [DengSir/tdPack2#2]
你好，能不能提供一个配置项，可以禁用 自动保存到银行(总是将银行的堆叠填满) 这个功能？
很多时候不想要它自动移动，比如一些药水类的消耗品，我希望总是将背包的堆叠填满而不是银行的，不然背包里就1 2个的时候一用就没了。
或者如果能提供配置：自动提取到背包(总是将背包的堆叠填满) 就更好了
感谢！

**Comment by SwimmingTiger** [comment]
这应该是个Bug，在不开“默认整理同时保存到银行”的情况下，背包内物品不应该在玩家没有察觉的情况下跑到银行。

但是目前，当银行打开，并且背包和银行里存在相同物品时，背包里的物品总是会意外跑到银行，这应该不至于是一个功能。

**Comment by SwimmingTiger** [comment]
我写了个补丁防止这种情况发生：
https://github.com/DengSir/tdPack2/pull/3

**Comment by DengSir** [comment]
在1.4.0版本添加了这个选项，感谢反馈
