### ISSUE TITLE
老哥能不能出一个可设置的反向整理,像以前的Jpack一样??

### ISSUE THREAD

**Issue by Tmalll** [DengSir/tdPack2#4]
老哥能不能出一个可设置的反向整理,像以前的Jpack一样??

**Comment by DengSir** [comment]
这个一直都有的哇

**Comment by Tmalll** [comment]
> 这个一直都有的哇

我意思是有个选项可以默认就反向整理,现在这个还得用命令,要把Combuctor的背包排列反过来... 总感觉怪怪的

**Comment by Tmalll** [comment]
> 这个一直都有的哇

怎么能把反向整理设置成系统默认的?

**Comment by DengSir** [comment]
在插件设置里面有个选项
