### ISSUE TITLE
Error in TBCC with TDPack2

### ISSUE THREAD

**Issue by ghost** [DengSir/tdPack2#5]
Date: 2021-05-23 22:41:31
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua line 33:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "@tdPack2\Libs\tdGUI\Widget\DropMenu.lua"]:33: ctor()
   [string "@tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua"]:61:
      ...s\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:53
   [string "=(tail call)"]: ?
   [string "@tdPack2\Libs\tdGUI\Widget\DropMenu.lua"]:329: in main chunk
Locals:
self = <unnamed> {
 0 = <userdata>
 menuList = <table> {
 }
 GetSelected = <function> defined @Interface\FrameXML\UIParent.lua:4487
 GetSelectedItem = <function> defined @Interface\FrameXML\UIParent.lua:4487
 IsSelected = <function> defined @Interface\FrameXML\UIParent.lua:4487
 scrollUp = TopScrollUpButton {
 }
 SetSelectedItem = <function> defined @Interface\FrameXML\UIParent.lua:4487
 _selectMode = "NONE"
 scrollDown = TopScrollDownButton {
 }
 scrollBar = <unnamed> {
 }
 _leftPadding = 15
 _buttons = <table> {
 }
 SetSelected = <function> defined @Interface\FrameXML\UIParent.lua:4487
}
_ = nil
style = "MENU"
withOtherMenu = nil
menuList = nil
level = 1
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 menuList = <table> {
 }
 GetSelected = <function> defined @Interface\FrameXML\UIParent.lua:4487
 GetSelectedItem = <function> defined @Interface\FrameXML\UIParent.lua:4487
 IsSelected = <function> defined @Interface\FrameXML\UIParent.lua:4487
 scrollUp = TopScrollUpButton {
 }
 SetSelectedItem = <function> defined @Interface\FrameXML\UIParent.lua:4487
 _selectMode = "NONE"
 scrollDown = TopScrollDownButton {
 }
 scrollBar = <unnamed> {
 }
 _leftPadding = 15
 _buttons = <table> {
 }
 SetSelected = <function> defined @Interface\FrameXML\UIParent.lua:4487
}
(*temporary) = <table> {
 bgFile = "Interface\Tooltips\UI-Tooltip-Background"
 tileSize = 16
 edgeFile = "Interface\Tooltips\UI-Tooltip-Border"
 edgeSize = 16
 tile = true
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
DropMenu = <table> {
 OnItemFormatting = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:230
 GetLevel = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:317
 Close = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:170
 OnItemEnter = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:257
 SuperCall = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:142
 Bind = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:88
 Toggle = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:152
 SetLevel = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:313
 GetOpenPosition = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:295
 GetSuper = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:99
 IsType = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:111
 OnHide = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:291
 CloseOtherMenu = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:175
 RefreshMenu = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:163
 IsInstance = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:125
 OnItemClick = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:196
 Open = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:98
 Constructor = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:22
 OnItemLeave = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:287
 Fire = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:136
 OnRefresh = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Widget\DropMenu.lua:183
 GetType = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:103
 New = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:81
 _Meta = <table> {
 }
 SetCallback = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:129
 GetInherit = <function> defined @Interface\AddOns\tdPack2\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:107
}
GUI = <table> {
 NewClass = <function> defined @Interface\AddOn

**Comment by DengSir** [comment]
fixed
