### ISSUE TITLE
TBC怀旧服在包里有钥匙且钥匙排序混乱的情况下，tdPack2无法完成背包整理

### ISSUE THREAD

**Issue by SwimmingTiger** [DengSir/tdPack2#7]
如图，点击整理按钮后，`Group:Pack()`和`Group:IsPackFinish()`一直在被调用，但是整理一直都没有完成，并且`self.items`里剩的都是钥匙。

钥匙串的`bagId`是`-2`，这可能导致了逻辑问题，在整理时错过了这个包。

![微信图片_20210810223002](https://user-images.githubusercontent.com/4986069/128885638-5699ab7e-4b9a-4a65-8d3e-61eb10729bb7.png)

**Comment by SwimmingTiger** [comment]
看起来并不是错过了`bagId` `-2`，另一个角色只有两把钥匙，无论怎么放都能完成整理。
也许是特定的钥匙导致了这个问题。

**Comment by SwimmingTiger** [comment]
网友说他钥匙串里的血色十字军钥匙可以导致整理卡住。

**Comment by DengSir** [comment]
仓库的代码需要处理过才能用的

**Comment by SwimmingTiger** [comment]
我们是从 https://www.curseforge.com/wow/addons/tdpack2/files/3355973 下载的

**Comment by SwimmingTiger** [comment]
一楼图片里聊天框中的信息是我为了调试目的而添加的

正则表达式替换：
`function(.*)`
   ->
`function$1 print('$1')`

-------------

上面提到的玩家关于他的钥匙导致整理卡住问题的详细描述：

> 我现在只有3把钥匙 只有调整血色十字军钥匙的时候 会卡住。
> 我存了3把钥匙 分别是血色十字军钥匙 月牙钥匙 通往灼热峡谷的大门钥匙。
> 但是我小号没有月牙钥匙，所以可能是血色十字军钥匙和灼热峡谷钥匙有某种冲突。
> 我现在把月牙钥匙放回钥匙链，就出现整理完成的情况了。
> 我只要把这两把钥匙存到银行，就OK了。

我还亲自查看了另一名玩家的情况，他有更多钥匙，也会导致整理卡住，就是一楼图片里的那些。

**Comment by SwimmingTiger** [comment]
我正在尝试获取血色十字军钥匙，以复现他们的问题。但是在他们的角色那里，问题都是可以稳定复现的。

另一个玩家（1楼图片）没有血色十字军钥匙，但有通往灼热峡谷大门的钥匙。第二个玩家也提到了该钥匙。

> 所以可能是血色十字军钥匙和灼热峡谷钥匙有某种冲突。

**Comment by DengSir** [comment]
这3把钥匙我都有，但是复现不了问题

**Comment by DengSir** [comment]
之前有一个问题，我是用travis打包上传的，在2.0.3发布后，travis  bug了，又发布了一次2.0.2版本，然后我在curse上删除了错误的2.0.2版本，但是桃乐豆更新器缓存了2.0.2版本，然后一直是那个版本

我这github issues总是回复不了，方便的话留个联系方式

**Comment by SwimmingTiger** [comment]
把这些钥匙放进钥匙链，然后打乱顺序，再按整理试试。如果问题发生，不会有整理完成的提示，然后后面再按整理按钮就没有反应了。

如果依然无法复现问题，方便的话你可以加我微信，我可以联系到有这个问题的玩家。我今天还远程控制了他们的电脑来查看问题。
![微信号：SwimmingTiger](https://file.hu60.cn/file-hash-png-96dd4d6ec17b2907934f09703acc39e469983.png)

**Comment by SwimmingTiger** [comment]
> 之前有一个问题，我是用travis打包上传的，在2.0.3发布后，travis bug了，又发布了一次2.0.2版本，然后我在curse上删除了错误的2.0.2版本，但是桃乐豆更新器缓存了2.0.2版本，然后一直是那个版本
> 
> 我这github issues总是回复不了，方便的话留个联系方式

确实是这样，我们用的版本是从桃乐豆下载的2.0.2，不是2.0.3……

更新到2.0.3后问题解决。
